package cluster

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"
)

// DefaultConfigTemplate is the content of the remote-kind.yaml generated by "remote-kind init".
const DefaultConfigTemplate = `# remote-kind cluster configuration
# Generated by: remote-kind init
#
# Run "remote-kind create cluster" to create this cluster.

apiVersion: remote-kind.x-k8s.io/v1alpha1
kind: Cluster
name: kind

spec:
  # Alibaba Cloud region and zone
  region: cn-beijing
  zone: cn-beijing-h

  # SSH public key for node access (optional)
  # sshKey: ~/.ssh/id_ed25519.pub

  # Control plane (ECS instance type)
  controlPlane:
    instanceType: ecs.e-c1m2.large   # 2 vCPU, 4 GiB

  # Worker nodes
  workers:
  - replicas: 1
    instanceType: ecs.e-c1m2.large

  # Networking (all optional — defaults shown)
  # networking:
  #   podSubnet: 10.244.0.0/16
  #   serviceSubnet: 10.96.0.0/12

  # CNI plugin
  cni: flannel

# Image build settings (used by "remote-kind build-image")
# build:
#   mirrors:
#     registry.k8s.io: <your-k8s-mirror>
#     docker.io: <your-docker-mirror>
#     ghcr.io: <your-ghcr-mirror>
`

// LoadConfig reads and parses a remote-kind.yaml file, applying defaults.
func LoadConfig(path string) (*ClusterConfig, error) {
	if !filepath.IsLocal(path) {
		return nil, fmt.Errorf("config path not local: %s", path)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read config %s: %w", path, err)
	}

	var cfg ClusterConfig
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return nil, fmt.Errorf("parse config: %w", err)
	}

	if cfg.Name == "" {
		return nil, fmt.Errorf("config must have a 'name' field")
	}
	if cfg.Kind != "Cluster" {
		return nil, fmt.Errorf("config 'kind' must be 'Cluster', got %q", cfg.Kind)
	}

	cfg.ApplyDefaults()
	return &cfg, nil
}

// ReadSSHKey reads and returns the SSH public key specified in the config.
func (c *ClusterConfig) ReadSSHKey() (string, error) {
	if c.Spec.SSHKey == "" {
		return "", nil
	}
	path := c.Spec.SSHKey
	if strings.HasPrefix(path, "~/") {
		home, _ := os.UserHomeDir()
		path = home + path[1:]
	}
	if !filepath.IsLocal(path) {
		return "", fmt.Errorf("ssh key path not local: %s", path)
	}
	keyBytes, err := os.ReadFile(path)
	if err != nil {
		return "", fmt.Errorf("read SSH key %q: %w", c.Spec.SSHKey, err)
	}
	return strings.TrimSpace(string(keyBytes)), nil
}

// WriteDefaultConfig writes the default configuration template to path.
func WriteDefaultConfig(path string) error {
	if _, err := os.Stat(path); err == nil {
		return fmt.Errorf("%s already exists", path)
	}
	return os.WriteFile(path, []byte(DefaultConfigTemplate), 0600)
}
